unique_ids:
  assets:
    standard-page.html: JKUZOHK73IXHK5KY67ZJHGW3KREJE7X3
    theme.css: KBQJ5ELKRSTW5YLDBTIC6RVPYNDGCPVE
  forms:
    Form1: JXYI767MFROGJO2IHJQTWDXC747MQIVS
  modules: {}
  scripts: {}
  server_modules: {}
