unique_ids:
  assets:
    standard-page.html: JKUZOHK73IXHK5KY67ZJHGW3KREJE7X3
    theme.css: KBQJ5ELKRSTW5YLDBTIC6RVPYNDGCPVE
  forms:
    Form1: JXYI767MFROGJO2IHJQTWDXC747MQIVS
  modules:
    Module1: '1760549011185133986307994.88332'
  scripts: {}
  server_modules:
    ServerModule1: '1760548916139614592679266.0887'
